config/routes.rb
# frozen_string_literal: true

WhiteRabbit::Engine.routes.draw do
  get 'index', action: :index, controller: 'admin'
  get 'tasks', action: :task_types, controller: 'admin'
  post 'create', action: :create, controller: 'admin'
  post 'run_job', action: :run_job, controller: 'admin'
  post 'destroy_job', action: :destroy_job, controller: 'admin'
  get 'scheduled_jobs', action: :fetch_jobs, controller: 'admin'
end

app/models/white_rabbit/application_record.rb
module WhiteRabbit
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/white_rabbit/task_model.rb
# frozen_string_literal: true
module WhiteRabbit
  class TaskModel < ApplicationRecord
    validates :interval, presence: true
    validates :job_id, presence: true
    validates :job_class, presence: true

    def self.save_task(task, job_id)
      create(
        job_class: task.class.to_s,
        job_id: job_id,
        interval: task.interval,
        params: task.params
      )
    end

    def readable_interval
      Cron2English.parse(interval).join(' ')
    rescue Cron2English::ParseException
      interval
    end
  end
end

app/controllers/white_rabbit/admin_controller.rb
require_dependency 'white_rabbit/application_controller'

module WhiteRabbit
  class AdminController < ApplicationController
    layout 'application' # use host applications layout

    def index
      @jobs = task_names
      @scheduled_jobs = TaskModel.all
      render :index
    end

    def create
      task = SchedulerService.create_task(create_job_params)

      if task
        redirect_to :index, flash: { notice: 'Task Created' }
      else
        redirect_to :index, flash: { alert: 'Couldn\'t create task' }
      end
    end

    def run_job
      params.permit(:job_class, :job_params, :authenticity_token, :commit)
      success = JobService.run_job(params[:job_class], params[:job_params])
      if success
        redirect_to :index, flash: { notice: 'Job triggered' }
      else
        redirect_to :index, flash: { alert: 'Couldn\'t run job' }
      end
    end

    def fetch_jobs
      render json: TaskModel.all.to_json(except: [:id, :interval], methods: :readable_interval)
    end

    def destroy_job
      res = SchedulerService.kill_task(params_for_destroy_job[:job_id])
      if res
        redirect_to :index
      else
        redirect_to :index, flash: { alert: "Couldn't kill the task" }
      end
    end

    private

    # TODO: cache this one
    def task_names
      root_path = Rails.root.join('app', 'schedule', 'white_rabbit')

      return [] unless Pathname.new(root_path).exist?

      file_names = Dir.entries(root_path)
      file_names
        .select { |fn| File.extname(fn) == '.rb' }
        .map { |fn| fn.gsub('.rb', '').camelize }
    end

    def params_for_destroy_job
      params.permit(:jobId).to_h.to_snake_keys.with_indifferent_access
    end

    def create_job_params
      params.permit(
        :cron,
        :jobParams,
        :jobType,
        :authenticity_token,
        :commit
      ).to_h.to_snake_keys.with_indifferent_access
    end
  end
end

app/controllers/white_rabbit/application_controller.rb
module WhiteRabbit
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/helpers/white_rabbit/admin_helper.rb
module WhiteRabbit
  module AdminHelper
    def month_options
      [['January', 1],
       ['February', 2],
       ['March', 3],
       ['April', 4],
       ['May', 5],
       ['June', 6],
       ['July', 7],
       ['August', 8],
       ['September', 9],
       ['October', 10],
       ['November', 11],
       ['December', 12]]
    end

    def days_of_week_options
      [['Sunday', 0], ['Monday', 1], ['Tuesday', 2], ['Wednesday', 3], ['Thursday', 4], ['Friday', 5], ['Saturday', 6]]
    end

    def days_option
      (1..31).to_a.each_with_index.map { |item, index| [item.to_s << 'th', index + 1] }
    end
  end
end

app/helpers/white_rabbit/application_helper.rb
module WhiteRabbit
  module ApplicationHelper
  end
end

app/views/layouts/white_rabbit/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Engine</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/white_rabbit/admin/index.html.erb
<div data-controller='admin' class="container">
<h1> Create Schedule </h1>
<% if flash.alert.present? %>
 <div class="alert alert-danger" role="alert">
  <%= flash.alert %>
 </div>
<% end %>

<% if flash.notice.present? %>
  <div class="alert alert-success" role="alert">
   <%= flash.notice %>
  </div>
<% end %>

<%= form_with url: create_path do |f|  %>
  <div class="form-group row">
    <label class="col-4 col-form-label" for="select">Jobs</label>
    <div class="col-8">
      <%= select_tag "jobType",  options_for_select(@jobs), class: "custom-select", "data-target": "admin.job"  %>
    </div>
  </div>
  <div class="form-group row">
    <label for="text" class="col-4 col-form-label">Params</label>
    <div class="col-8">
      <input id="text" name="jobParams" type="text" class="form-control" data-target="admin.jobParams">
    </div>
  </div>

  <div class="form-group row">
    <label for="text" class="col-4 col-form-label">Cron Expression</label>
    <div class="col-8">
      <input id="cron" name="cron" type="text" class="form-control" data-action="input->admin#checkCron" data-target="admin.cronExpression">
    </div>
  </div>

  <div class="form-group row">
    <label for="text" class="col-4 col-form-label">Quick Schedule</label>
    <div class="col-8">
      <button type="button" data-exp = "*/1 * * * *" class="btn btn-info" data-action="admin#quickSchedule">Every Minute</button>
      <button type="button" data-exp = "0 8 * * *" class="btn btn-info" data-action="admin#quickSchedule">Daily 8 AM</button>
      <button type="button" data-exp = "0 0 1 * *" class="btn btn-info" data-action="admin#quickSchedule">First day of month</button>
    </div>
  </div>

  <div class="form-group row">
    <div class="offset-4 col-8">
       <%= f.submit 'Create Job', id: 'submitButton', class: 'btn btn-primary', "data-target": 'admin.submitButton' %>
    </div>
  </div>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Job Name</th>
      <th scope="col">Interval</th>
      <th scope="col">Params</th>
    </tr>
  </thead>
  <tbody data-target="admin.status">
     <% @scheduled_jobs.each_with_index do |scheduled_job, index| %>
       <tr>
       <td> <%= index + 1 %></td>
       <td> <%= scheduled_job.job_class %> </td>
       <td> <%= scheduled_job.readable_interval %>  </td>
       <td> <%= scheduled_job.params %> </td>
      <td>
       <%= form_with url: destroy_job_path,   method: :post  do |f| %>
          <%= f.hidden_field :jobId, :value => scheduled_job.job_id %>
           <%= f.submit 'Delete', class: 'btn btn-danger'  %>
       <% end %>
       </td>
       <td>
         <%= form_with url: run_job_path,   method: :post  do |f| %>
            <%= f.hidden_field :job_class, :value => scheduled_job.job_class %>
            <%= f.hidden_field :job_params, :value => scheduled_job.params %>
            <%= f.submit 'Run Now', class: 'btn btn-primary'  %>
         <% end %>
       </td>
       </tr>
     <% end %>
  </tbody>
</table>
<%= stylesheet_link_tag  '/assets/white_rabbit', media: 'all', 'data-turbolinks-track': 'reload'  %>
<%= javascript_include_tag '/assets/white_rabbit' %>
</div>